db_port: 3306
db_name: "crud_react_node"
db_user: "root"
db_password: "{{ vault_mysql_root_password }}"

# App configurations
NODE_ENV: development
PORT: 3000

env_backend:
  NODE_ENV: development
  PORT: 3000
  DB_HOST: "{{ db_host | default('localhost') }}"  # Will be set by inventory
  DB_USER: "{{ db_user }}"
  DB_PASS: "{{ db_password }}"
  DB_NAME: "{{ db_name }}"
  BACKEND_HOST: "0.0.0.0"