# Generated by Terraform - do not edit
[bastion]
bastion ansible_host=${bastion_public_ip} ansible_user=${bastion_user} ansible_ssh_private_key_file=${ssh_key_path}

[app]
%{ for name, ip in app_hosts ~}
${name} ansible_host=${ip} ansible_user=${app_db_user} ansible_ssh_private_key_file=${ssh_key_path} ansible_ssh_common_args="-o ProxyJump=${bastion_user}@${bastion_public_ip}"
%{ endfor ~}

[all:vars]
ansible_python_interpreter=/usr/bin/python3
