# Generated by Terraform - copied to the bastion by the Ansible playbook
Host bastion
  HostName ${bastion_public_ip}
  User ${bastion_user}
  IdentityFile ${bastion_key_path}
  StrictHostKeyChecking no

%{ for name, ip in app_hosts ~}
Host ${name}
  HostName ${ip}
  User ${app_db_user}
  IdentityFile ${bastion_key_path}
  StrictHostKeyChecking no

%{ endfor ~}
