[bastion]
bastion-primary ansible_host=3.219.217.224 ansible_user=ec2-user

[app]
app-server-1 ansible_host=10.0.10.183 ansible_user=ec2-user
app-server-2 ansible_host=10.0.10.161 ansible_user=ec2-user

[db]
db-server-1 ansible_host=10.0.10.34 ansible_user=ec2-user

[parent:children]
app
db

[bastion:vars]
ansible_ssh_private_key_file=./ansible/ssh_key.pem

[parent:vars]
ansible_ssh_private_key_file=./ansible/ssh_key.pem
ansible_ssh_common_args=-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %%h:%%p -i './ansible/ssh_key.pem' -o StrictHostKeyChecking=no ec2-user@3.219.217.224"


[all:vars]
ansible_python_interpreter=/usr/bin/python3