---
- name: Setup MySQL on Amazon Linux
  hosts: db
  become: true
  vars_files:
    - vault.yml
    - group_vars/db.yml
  roles:
    - db


- name: Build Frontend and Prepare backend
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars_files:
    - vault.yml
    - group_vars/app.yml
  tasks:
    - name: Include build tasks
      include_tasks: "roles/app/tasks/build-local.yml"

- name: Deploy Application Stack
  hosts: app
  become: true
  vars_files:
    - vault.yml
    - group_vars/app.yml
  roles:
    - app